# MCU name
MCU = STM32F303

# Build Options
#   comment out to disable the options.
#
FIRMWARE_FORMAT = bin
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
NKRO_ENABLE = yes
UNICODE_ENABLE = yes
RGB_MATRIX_ENABLE = IS31FL3733
